doctrine:
    dbal:
      # Set the default connection to default
      #'DATABASE_URL' => 'mysql://root@127.0.0.1:3306/controlmud?serverVersion=mariadb-10.4.11',
      default_connection: default
      connections:
        default:
                driver: pdo_mysql
                host: '127.0.0.1'
                port: '3306'
                dbname: 'controlmud'
                user: 'root'
                password:  ''
                charset: UTF8
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        default_entity_manager: default
        entity_managers:
            # Register which bundle should use which connection
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
